### ISSUE TITLE
readlink -f fails on osx

### ISSUE THREAD

**Issue by seanjensengrey** [un-def/luamb#1]
Modified luamb to use `greadlink` from `brew install coreutils`

**Comment by un-def** [comment]
I've added OS check with automatic readlink/greadlink selection.

Please test the new version:

```
pip install git+https://github.com/un-def/luamb.git
```

**Comment by seanjensengrey** [comment]
Tested main path, 👍  Didn't uninstall `coreutils` and test error path.
